config/routes.rb
Rails.application.routes.draw do

  resources :blogs do
      post :confirm, on: :collection
      patch :edit_confirm, on: :member
      resources :comments
  end
  
  resources :contacts, only: [:new, :create, :show, :confirm ] do
  end
  
  resources  :tops, only: [:index] do
  end
  
  resources  :users do
  end

  resources  :sessions, only:[:new, :create, :destroy]
  
  resources  :favorites, only:[:create, :destroy]
  
  resources  :relationships, only:[:create, :destroy]
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  root to: 'tops#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true 
  validates :content, length: {in: 1..140}
  
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  

  mount_uploader :image, ImageUploader
  
  has_many :comments, dependent: :destroy
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :content, length: {in: 1..140}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :blog
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  
  has_secure_password
  
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  
  before_save {email.downcase!}
  
  has_many :blogs, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog
  
  mount_uploader :image, ImageUploader
  
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  
  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end
  
  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end
  
  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :edit_confirm]
  before_action :login, only: [:new, :edit, :show, :destroy]

  def index
    @blogs = Blog.all
  end

  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end

  def create
    @blog = Blog.create(blog_params)
    @blog.user_id = current_user.id
    @blog.image.retrieve_from_cache! params[:cache][:image]
    
    respond_to do |format|
      if @blog.save
        MakeblogMailer.makeblog_mail(@blog).deliver
        format.html { redirect_to blogs_path, notice: 'Blog was successfully created.' }
        format.json { render :index, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
    
    @comment  = @blog.comments.build
    @comments = @blog.comments 
  end

  def edit
  end
  
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        MakeblogMailer.makeblog_mail(@blog).deliver  
        format.html { redirect_to blogs_path, notice: 'Blog was successfully updated.' }
        format.json { render :index, status: :created, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end


  def confirm
    @blog = Blog.new(blog_params)
    render :new  if @blog.invalid?
  end
  
  def edit_confirm
    @blog = Blog.new(blog_params)
    @blog.id = params[:id]
    render :edit  if @blog.invalid?
  end

    
  private
  def blog_params
    params.require(:blog).permit(:title,:content, :image, :image_cache)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end
  
  def login
    if not logged_in?
      redirect_to new_session_path
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.build(comment_params)
    
    respond_to do |format|
      if @comment.save
        format.js{render :index}
      else
        format.html{redirect_to blog_path(@blog), notice: "投稿してない" }
      end
    end
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:blog_id, :content)
  end
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only:[:show, :edit, :update, :destroy]
  
  def index
    @contacts = Contacts.all
  end

  def new
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(contact_params)
      
    respond_to do |format|
      if @contact.save
        ContactMailer.contact_mail(@contact).deliver
        format.html{ redirect_to @contact, notice:'送信されました'}
        format.json{ render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end
  
  private
  
  def set_contact
    @contact = Contact.find(params[:id])
  end
  
  def contact_params
    params.require(:contact).permit(:name,:email,:content)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}のブログをお気に入りしました"
  end
  
  def destroy
    favorite = current_user.favorites.find_by(blog_id: params[:blog_id]).destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}のブログのお気に入りを解除しました"
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログイン失敗'
      render 'new'
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to new_session_path
  end
  
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  
  def index
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      redirect_to user_path(@user.id)
    else 
      render 'new'
    end

  end
  
  def show
    @user = User.find(params[:id])
    @favorite_blogs = @user.favorite_blogs
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == "new" || action_name == "confirm"  
      confirm_blogs_path
    elsif action_name == "edit" || action_name == "edit_confirm"
      edit_confirm_blog_path
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end

end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<div class="container">
  
  <%= form_with(model: @blog, local: true, url: choose_new_or_edit) do |form| %>
  
      <% if @blog.errors.any? %>
        <div id="error_explanation">
          <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
          <ul>
    
          <% @blog.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="form_group row">
        <p class="col-xs-12 col-md-offset-2 col-md-3"><%= form.label :title %></p>
        <p class="col-xs-12 col-md-5"><%= form.text_field :title %></p>
      </div>
      
      <div class="form_group row">
        <p class="col-xs-12 col-md-offset-2 col-md-3"><%= form.label "　内容　" %></p>
        <p class="col-xs-12 col-md-5"><%= form.text_field :content %></p>
      </div>
      
      <div class="field">
        <p class="col-xs-12 col-md-offset-2 col-md-3"><%= form.label :image %></p>
        <p class="col-xs-12 col-md-5"><%= form.file_field :image, id: :blog_image %></p>
        <%= image_tag(@blog.image.url) if @blog.image.url %>
        <%= form.hidden_field :image_cache %>
      </div>
      
      <br>
      
      <p><%= form.submit class: "btn btn-primary" %></p>
    
     
      
    <% end %>
    
    <br>
    <%= link_to "ブログ一覧画面にもどる", blogs_path %>
     
</div>

app/views/blogs/confirm.html.erb
<%= form_with(model: @blog, local: true) do |form| %>
<%#= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= hidden_field_tag :"cache[image]",@blog.image.cache_name %>

  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %><%= image_tag(@blog.image.url) %></p>
  
  <%= form.submit  "登録する",class:"btn btn-primary" %>
  
<% end %>


<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.submit "もどる", name: 'back'%>
  <%= hidden_field_tag :"cache[image]",@blog.image.cache_name %>
<% end %>

app/views/blogs/edit.html.erb
<h1>ブログを編集する</h1>

<br>

<%= render 'form' %>

app/views/blogs/edit_confirm.html.erb
<%= form_with(model: @blog, url: blog_path, local: true, method: 'patch') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>

  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %><%= image_tag(@blog.image.url) unless @blog.image.blank? %></p>
  
  
  <%= form.submit  "更新する",class:"btn btn-primary" %>
  
<% end %>

<%= form_with(model: @blog, url: edit_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.submit "もどる", name: 'back'%>
<% end %>

app/views/blogs/index.html.erb
<h1>ブログ一覧</h1>

<p><%= notice %></p>

<div class="table-responsive">
  <table class="table">
   <% @blogs.each do |blog| %>
     <tr>
       <th>ユーザー名</th> 
       <th>タイトル</th>
     </tr>
     <tr>
       <td><%= image_tag blog.user.image, class: "icon" %><p><%= blog.user.name %>さん</p></td>
       <td><%= blog.title %></td>
       <td><%= link_to '詳細', blog_path(blog.id) %></td>
       <td><%= link_to "編集", edit_blog_path(blog.id) %></td>
       <td><%= link_to '削除', blog_path(blog.id), method: :delete,
            data:{confirm:'このブログを削除してよろしいですか？'} %></td>
     </tr>
   <% end %>
  </table>
</div>

  
<%= link_to '新規作成', 'blogs/new' %>

app/views/blogs/new.html.erb
<h1>ブログを作成する</h1>

<br>

<%= render 'form' %>

app/views/blogs/show.html.erb
<h1>ブログ詳細画面</h1>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %><%= image_tag @blog.image %></p>

<% unless @blog.user_id == current_user.id %>
  <% if @favorite.present? %>
     <%= link_to 'お気に入り解除', favorite_path(id: @favorite.id, blog_id: @blog.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
     <%= link_to 'お気に入り', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<p>コメント一覧</p>
<div id="comments_area">
  <%= render partial: 'comments/index', locals: {comments: @comments, blog: @blog} %>
</div>

<%= render partial: 'comments/form', locals: {comment: @comment, blog: @blog} %>

<%= link_to '一覧に戻る', '/blogs' %>

app/views/comments/_form.html.erb
<%= form_with(model:[blog,comment]) do |form| %>
   <% if comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(comment.errors.count, "error") %></h2>
        <ul>
          <% comment.errors.full_messages.each do |message| %>
             <li><%= message %></li>
          <% end %>
        </ul>
      </div>
   <% end %>
   
   <div class="field">
     <%= form.label :content %>
     <%= form.text_area :content %>
   </div>
   
   <div class="action">
     <%= form.submit %>
   </div>
      
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
      <li>
        <p><%= comment.content %></p>
      </li>
    <% end %>
  <% end %> 
</ul>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.blog.comments, blog: @comment.blog }) %>")
$("textarea").val('')

app/views/contacts/new.html.erb
<div class="row">

<h1>お問い合わせ</h1>

<%= form_with(model:@contact, local:true) do |form| %>

  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h1><%= @contact.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="container">
          <div class="name row">
            <p class="col-xs-12 col-md-offset-2 col-md-3"><%= form.label :name %></p>
            <p class="col-xs-12 col-md-5"><%= form.text_field :name %></p>
          </div>
          <div class="email row">
            <p class="col-xs-12 col-md-offset-2 col-md-3"><%= form.label :email %></p>
            <p class="col-xs-12 col-md-5"><%= form.text_field :email %></p>
          </div>
           <div class="content row">
            <p class="col-xs-12 col-md-offset-2 col-md-3"><%= form.label :content %></p>
            <p class="col-xs-12 col-md-5"><%= form.text_field :content %></p>
          </div>
  </div>
   <br>
  <%= form.submit %>
<% end %>

app/views/contacts/show.html.erb
<p><%= notice %></p>
<p>名前: <%= @contact.name %></p>
<p>メール: <%= @contact.email %></p>
<p>内容: <%= @contact.content %></p>

<%= link_to '戻る', '/contacts/new' %> 

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user.following?(user) %>
    <%= form_with(model: current_user.active_relationships.new(followed_id: user.id)) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete ) do |f| %>
      <%= f.submit "つながりを解除" %>
    <% end %>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<% @users.each do |user| %>
  <%= user.name %>
  <%= render 'follow_form', user: user %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>


<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<div class="container">
  <%= form_with(model: @user, local: true) do |f| %> 
    <div class="row">
       <p class="col-xs-12 col-md-offset-2 col-md-3"><%= f.label :name %></p>
       <p class="col-xs-12 col-md-5"><%= f.text_field :name %></P>
    </div>
   
    <div class="row">
       <p class="col-xs-12 col-md-offset-2 col-md-3"><%= f.label :email %></p>
       <p class="col-xs-12 col-md-5"><%= f.email_field :email %></p>
    </div>
    
    <div class="row">
       <p class="col-xs-12 col-md-offset-2 col-md-3"><%= f.label :password %></p>
       <p class="col-xs-12 col-md-5"><%= f.password_field :password %></p>
    </div>
    
    <div class="row">
       <p class="col-xs-12 col-md-offset-2 col-md-3"><%= f.label :password_confirmation %></p>
       <p class="col-xs-12 col-md-5"><%= f.password_field :password_confirmation %></p>
    </div>
    
    <div class="row">
       <p class="col-xs-12 col-md-offset-2 col-md-3"><%= f.label :image %></p>
       <p class="col-xs-12 col-md-5"><%= f.file_field :image %></p>
       <%= f.hidden_field :image_cache %>
    </div>
    
    <%= f.submit "Create my account" %>
    
  <% end %>
</div>

app/views/users/show.html.erb
<p>ユーザー: <%= @user.name %></p>
<p>メールアドレス: <%= @user.email %></p>
<div class="box">
  <p><%= image_tag @user.image, class: "icon" %></p>
</div>

<br>

<% @favorite_blogs.each do |blog| %>
　<p>お気に入りブログ一覧</p>
  <p>
    <tr>
      <td><%= blog.title %></td>
      <td><%= link_to '詳細', blog_path(blog.id) %></td>
    </tr>
  </p>
<% end %>

<br>

<%= link_to "ブログ一覧画面へ", blogs_path %>