config/routes.rb
Rails.application.routes.draw do

  resources :blogs do
      post :confirm, on: :collection
      patch :edit_confirm, on: :member
      resources :comments
  end
  
  resources :contacts, only: [:new, :create, :show, :confirm ] do
  end
  
  resources  :tops, only: [:index] do
  end
  
  resources  :users do
  end

  resources  :sessions, only:[:new, :create, :destroy]
  
  resources  :favorites, only:[:create, :destroy]
  
  resources  :relationships, only:[:create, :destroy]
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  root to: 'tops#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true 
  validates :content, length: {in: 1..140}
  
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  

  mount_uploader :image, ImageUploader
  
  has_many :comments, dependent: :destroy
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :content, length: {in: 1..140}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :blog
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  
  has_secure_password
  
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  
  before_save {email.downcase!}
  
  has_many :blogs, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog
  
  mount_uploader :image, ImageUploader
  
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  
  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end
  
  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end
  
  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :edit_confirm]
  before_action :login, only: [:new, :edit, :show, :destroy]

  def index
    @blogs = Blog.all
  end

  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end

  def create
    @blog = Blog.create(blog_params)
    @blog.user_id = current_user.id
    @blog.image.retrieve_from_cache! params[:cache][:image]
    
    respond_to do |format|
      if @blog.save
        MakeblogMailer.makeblog_mail(@blog).deliver
        format.html { redirect_to blogs_path, notice: 'Blog was successfully created.' }
        format.json { render :index, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
    
    @comment  = @blog.comments.build
    @comments = @blog.comments 
  end

  def edit
  end
  
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        MakeblogMailer.makeblog_mail(@blog).deliver  
        format.html { redirect_to blogs_path, notice: 'Blog was successfully updated.' }
        format.json { render :index, status: :created, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end


  def confirm
    @blog = Blog.new(blog_params)
    render :new  if @blog.invalid?
  end
  
  def edit_confirm
    @blog = Blog.new(blog_params)
    @blog.id = params[:id]
    render :edit  if @blog.invalid?
  end

    
  private
  def blog_params
    params.require(:blog).permit(:title,:content, :image, :image_cache)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end
  
  def login
    if not logged_in?
      redirect_to new_session_path
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.build(comment_params)
    
    respond_to do |format|
      if @comment.save
        format.js{render :index}
      else
        format.html{redirect_to blog_path(@blog), notice: "投稿してない" }
      end
    end
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:blog_id, :content)
  end
  
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  
  def index
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      redirect_to user_path(@user.id)
    else 
      render 'new'
    end

  end
  
  def show
    @user = User.find(params[:id])
    @favorite_blogs = @user.favorite_blogs
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == "new" || action_name == "confirm"  
      confirm_blogs_path
    elsif action_name == "edit" || action_name == "edit_confirm"
      edit_confirm_blog_path
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end

end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Sample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
   
    
  </head>

  <body>
    <div class="container">
        <header class="header">
          <nav class="navbar navbar-default">
            <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
                  <span class="sr-only">blog</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">miniBlog</a>
              </div>
              <div id="gnavi" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                  <li><%= link_to "TOP", tops_path %></li>
                  <li><%= link_to "一覧", blogs_path %></li>
                  <li><%= link_to "お問い合わせ", new_contact_path %></li>
                  <% if logged_in? %>
                      <li>
                        <nav class="navbar navbar-default">
                            <ul class="nav navbar-nav">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    マイアカウント
                                    </a>
                                    <ul class="dropdown-menu">
                                      <li><%= image_tag current_user.image, class: "icon_for_header" %></li>
                                      <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
                                      <li><%= link_to "お気に入り", user_path(current_user.id) %></li>
                                      <li><%= link_to 'ユーザー一覧', users_path  %></li>
                                    </ul>
                                </li>
                            </ul>
                        </nav>
                      </li>
                  <% else %>
                      <li><%= link_to "新規登録", new_user_path %></li>
                      <li><%= link_to "ログイン", new_session_path %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          </nav>
        </header>

      <%= yield %>
      
      <footer class="fixed-bottom">
        <p>白鳥雄大</p>
      </footer>
      
    </div>
  </body>
</html>